### ISSUE TITLE
Midterm2 第2題、第3-2題

### ISSUE THREAD

**Issue by yoyochingyu** [tpemartin/107-2-inclass-practice#20]
想請老師再幫我看一下第二題錯的地方！

另一點是第3-2題，
我了解if-else不能適用於多個邏輯判斷值(只會判斷第一個)，但由於我在程式前幾行就先設定的c(101,104,105,107)是按照排序的，也就是說只要entrance year>=101就一定找得到資料，想請問這題錯誤的地方為何呢？

感謝老師
沁妤

**Comment by tpemartin** [comment]
2：字串不能和數字直接比喔。

3.2：
`if(numofyear <= entranceYear)`要改成`if(any(numofyear <= entranceYear))`，不然它的logical值會不唯一（if的條件只能有一個TRUE/FALSE, 要避免出現多個T/F 值）

要提一下，你的設計很棒。

**Comment by yoyochingyu** [comment]
Martin老師你好，

2：
我了解字串應該是不能直接和數字比較大小的，但我在那天以及之前嘗試的時候，以字串直接和數字比較都能執行出正確的結果耶？想知道為什麼會這樣><

3-2：
我理解寫成i f(numofyear <= entranceYear) 邏輯判斷會不唯一，那這題更好的寫法是不是可以直接寫if(101<=entraceYear) ，因為唯有entrance year<=101才會找不到該筆資料呢？

感謝老師
沁妤

**Comment by tpemartin** [comment]
2. 每組字在電腦都會有個排序數字，這數字怎麼排受到電腦locale設定不同而影響，所以你給了個因電腦而異的答案。老師會建議不要再字串比數字了，它會跑出答案，但不會出現error，是不容易detect的bug，要改掉這習慣。

3-2：你建議的寫法也行。

**Comment by yoyochingyu** [comment]
了解了，感謝老師！！

沁妤
