### ISSUE TITLE
midterm2

### ISSUE THREAD

**Issue by amypiggy** [tpemartin/107-2-inclass-practice#21]
老師您好，我的作業代碼是MIDTERM2_094
我想說我真的有認真在準備考試，但是Midterm2考出來真的還是沒辦法...
因為真的很怕被當，所以厚著臉皮來請問老師有些有打出來的是否可以**部份給分**?
以下:

Q1.1
真的只差 stringsAsFactors = FALSE 其他都一模一樣了

Q3.1
少了list裡面的list
我的答案如下
EconCourseSelectionInfo <- list(
  "101" = "http://www.econ.ntpu.edu.tw/econ/files/Way/2016072195021.doc",
  "104" = "http://www.econ.ntpu.edu.tw/econ/files/Way/2016072195041.doc",
  "105" = "http://www.econ.ntpu.edu.tw/econ/files/Way/20170516144353.doc",
  "107" = "http://www.econ.ntpu.edu.tw/econ/files/Way/20180518121643.pdf"
)
EconCourseSelectionInfo

Q4Q5雖然都錯
但是應該真的能看出來我有盡力的複習上一次midterm
老師今天有說不應該是看你的答案去想
但是真的想不出來了，不過也有盡力理解老師的答案了
結果答題還是答成這樣...

Q4的話我好像真的錯太多了

不過想請問Q5
是不是前面的str_replace存回去 sampledTranscriptData$系級 就可以了
str_replace(sampledTranscriptData$系級,"1","")
str_replace(sampledTranscriptData$系級,"2","")
str_replace(sampledTranscriptData$系級,"3","")
str_replace(sampledTranscriptData$系級,"4","")
str_sub(sampledTranscriptData$學號,5,6) -> sampledTranscriptData$系碼
(sampledTranscriptData$系碼 != 73 & sampledTranscriptData$系級 == "經濟學系") -> changeMajorStudent1
unique(changeMajorStudent1) -> changeMajorStudent
changeMajorStudent

謝謝老師撥空看
誠心希望R能過的學生敬上

**Comment by tpemartin** [comment]
Q1.1 可以算對，其他部份是程式設計應要培養的正確使用概念，無法算對喔。

老師更新完會通知大家

**Comment by amypiggy** [comment]
好的，謝謝老師!
