### ISSUE TITLE
midterm2

### ISSUE THREAD

**Issue by alice880903** [tpemartin/107-2-inclass-practice#23]
老師您好，關於這次的考試我真的很認真準備了
只是我好像真的沒什麼天份...
所以想來求情
我第一題只差stringsAsFactors = FALSE其他都一模一樣了
可否請老師給我一點同情分
謝謝老師
真心希望自己可以不要被當的學生上

**Comment by alice880903** [comment]
老師我忘了說，我的學號是410773059
在這裡補上，謝謝老師

**Comment by alice880903** [comment]
老師我忘了說，我的學號是410773059
在這裡補上，謝謝老師

**Comment by tpemartin** [comment]
Q1.1 可以算對。

老師更新完會通知大家
