### ISSUE TITLE
midterm2

### ISSUE THREAD

**Issue by yuchuyin** [tpemartin/107-2-inclass-practice#24]
老師你好~

我的代碼是 MIDTERM2_028

Q1.1 我沒有打 stringASFactor=F 其他code 都一樣

Q4 我的code如下  
(在考試時太緊張 我忘了打下面**標記**的地方 可否給分?)

at<-invoiceList$訂單時區=="Asia/Taipei"
ny<-invoiceList$訂單時區=="America/New_York"

invoiceList$UTC時間**[at]**
<-with_tz(ymd_hms(invoiceList$`訂單時間(以訂單時區顯示)`[at],tz="Asia/Taipei"),tzone="UTC")
invoiceList$UTC時間**[ny]**
<-with_tz(ymd_hms(invoiceList$`訂單時間(以訂單時區顯示)`[ny],tz="America/New_York"),tzone="UTC")
invoiceList
謝謝老師~

**Comment by tpemartin** [comment]
Q1.1 okay

Q4. 無法給分
