### ISSUE TITLE
midterm2check

### ISSUE THREAD

**Issue by ArthurGuangTing** [tpemartin/107-2-inclass-practice#25]
老師你好
我的代碼是MIDTERM2_083
Q2 我的code如下
str_smallClosest <- function(chrNumber,criticalNumber){
  yes <- chrNumber<= criticalNumber
  choose <- c(as.integer(chrNumber)*yes)
  answer <- max(choose)
  require <- as.character(answer)
  return(require)
}
str_smallClosest
在更改過輸入的數字後仍是可以執行的
還請老師再檢查一下，謝謝老師

**Comment by tpemartin** [comment]
在老師電腦：
```
str_smallClosest(c("1","12","7"),6) 
```
會得到"12", 而非正確的"1"。

**Comment by tpemartin** [comment]
以下是我回覆另一位同學相同問題：

每個字、詞在電腦是有個排序位置，這個排序位置數字在遇到「字串比數字」時會被拿來和數字相比大小，然而這數字怎麼排受到電腦locale（使用者國家，使用者文字，等等）設定不同而影響，所以你給了個因電腦而異的答案。（有可能你電腦試會對，在我的電腦試會錯）

老師會建議不要再字串比數字了，它會跑出答案且常常不會對，更麻煩點是你程式不會出現error警訊，是不容易detect的bug，一定要改掉這習慣。否則這不良習慣會被你帶到其他程式語言裡。
