### ISSUE TITLE
FINAL_410773116期末考

### ISSUE THREAD

**Issue by yinghsuan726** [tpemartin/107-2-inclass-practice#26]
FINAL_410773116
4.1時區轉換函數
老師您好，我的程式碼和答案對照過了，應該是一樣的，但批改出來是錯的，我想知道在哪裡出了問題，謝謝老師。
以下是我的程式碼：
tzChange<-function(chrDateTimeInput,fromTz,toTz){
  with_tz(ymd_hms(chrDateTimeInput,tz=fromTz),tzone=toTz)->a
  as.character(a)
  return(a)
}
tzChange
以下是老師給的答案：
## ----ans41f--------------------------------------------------------------
tzChange <- function(chrDateTimeInput,fromTz,toTz){
  return(
    as.character(
      with_tz(
        ymd_hms(chrDateTimeInput,tz=fromTz),
        tzone=toTz
      )
    )
  )
}

tzChange

**Comment by tpemartin** [comment]
可否給正確檔案代碼，不是妳學號碼喔。在email裡有寫。

**Comment by yinghsuan726** [comment]
好的，老師不好意思，FINAL_120

**Comment by tpemartin** [comment]
as.character(a) 要改成
as.character(a) -> a
才會真的改了class

**Comment by tpemartin** [comment]
這個錯誤我再等看看有多少人有一樣的小粗心，可能會放寬算對。

**Comment by yinghsuan726** [comment]
好的我了解了，謝謝老師！

**Comment by tpemartin** [comment]
這裡我決定給你8分

**Comment by yinghsuan726** [comment]
ㄏ好的！謝謝老師！
