### ISSUE TITLE
410773011

### ISSUE THREAD

**Issue by eating1021** [tpemartin/107-2-inclass-practice#27]
老師您好，我的期末考檔案代碼是FINAL_027
想請問第一題批改後為什麼是錯的
以下為我的程式
## ----ans1f---------------------------------------------------------------
# str_smallClosest
str_smallClosest<-function(chrNumber,criticalNumber){
  as.numeric(chrNumber)->numNumber
  nunNumber<=criticalNumber->logiTrue
  max(numNumber[logiTrue])->maxNum
  return(as.character(maxNum))
}
str_smallClosest

以下為老師的參考答案
## ----ans1f---------------------------------------------------------------
str_smallClosest <- function(chrNumber,criticalNumber){
  as.numeric(chrNumber) -> numNumber
  logiTrue <- numNumber <= criticalNumber
  max(numNumber[(numNumber <= criticalNumber)]) -> maxNum
  return(as.character(maxNum))
}

str_smallClosest

**Comment by tpemartin** [comment]
`nunNumber<=criticalNumber->logiTrue`

這行有錯字`nunNumber`錯了。

這題我可以給5分
