### ISSUE TITLE
FINAL_074

### ISSUE THREAD

**Issue by Lihsin0816** [tpemartin/107-2-inclass-practice#28]
FINAL_074
老師您好
想請問老師第一題要怎麼修改，我不知道我是哪邊出錯了
（我剛試過可以跑得出答案）              學號：410773019
謝謝老師 
## ----ans1f---------------------------------------------------------------
str_smallClosest <- function(chrNumber,criticalNumber){
  as.numeric(chrNumber) -> chrNumber
  logiNum <- (as.character(chrNumber) <= criticalNumber)
  maxNum <- max(chrNumber[logiNum])
  return(maxNum)
}
str_smallClosest(c(10,12,11),13)
str_smallClosest
# str_smallClosest

參考答案
## ----ans1f---------------------------------------------------------------
str_smallClosest <- function(chrNumber,criticalNumber){
  as.numeric(chrNumber) -> numNumber
  logiTrue <- numNumber <= criticalNumber
  max(numNumber[(numNumber <= criticalNumber)]) -> maxNum
  return(as.character(maxNum))
}

str_smallClosest

**Comment by tpemartin** [comment]
跑得出答題不表示是對的答案，這裡有幾個步驟是錯的：

as.numeric(chrNumber) -> chrNumber
logiNum <- (as.character(chrNumber) <= criticalNumber) （1）
maxNum <- max(chrNumber[logiNum]) (2）
return(maxNum)

***

(1) 會是字串比數字，要改成 ： `logiNum <- (chrNumber <= criticalNumber)`

(2) 因為上面改了，這裡要改成：`maxNum <- as.character(max(chrNumber[logiNum]))`

***

字串比數字是重大錯誤，無法給任何分喔😅。

**Comment by Lihsin0816** [comment]
好的 謝謝老師！
