### ISSUE TITLE
FINAL_043

### ISSUE THREAD

**Issue by yuenchen00** [tpemartin/107-2-inclass-practice#29]
老師您好 我的學號是410473051
我想請教我的第三題及第四題 寫法跟解答差不多 但是跑出來都是錯的 想請問老師要如何修正
以及第一題的錯誤是因為最後沒有轉成字串return嗎
 謝謝老師~

**Comment by tpemartin** [comment]
第三題：
```
ymd_hms(q[ny],"America/New_York") ->h # 錯誤
ymd_hms(q[ny],tz="America/New_York") -> h # 正確
```

查詢ymd_hms使用說明會發現它的第二個input argument不會是tz而是一個叫quiet的input argument，所以"America/New_York"會是quiet的input value。在R裡若「不依input argument定義順序」給Input value，則該input要寫上其原始內定的input名稱，即這裡的tz。

第四題也是相同問題

**Comment by tpemartin** [comment]
第一題的確是沒轉字串原因。這題可以部份給分，給你5分。
