### ISSUE TITLE
FINAL_085

### ISSUE THREAD

**Issue by 0803tina** [tpemartin/107-2-inclass-practice#30]
FINAL_085
老師您好，想問我4-1這裡是哪裡錯了，我執行的時候答案一樣，謝謝老師。
tzChange <- function(chrDateTimeInput,fromTz,toTz){
    chrDateTimeInput1 <- ymd_hms(chrDateTimeInput,tz = fromTz)
    chrDateTimeInput2 <- with_tz(chrDateTimeInput1,tz = toTz)
    return(chrDateTimeInput2)
}
tzChange

**Comment by tpemartin** [comment]
return題目有要求character class. 
```
return(chrDateTimeInput2) # 錯誤
return(as.character(chrDateTimeInput2)) # 正確
```

這題可以給你5分

**Comment by 0803tina** [comment]
好的，謝謝老師。
