### ISSUE TITLE
FINAL_048

### ISSUE THREAD

**Issue by ailienchen** [tpemartin/107-2-inclass-practice#31]
老師您好:
可以請問為甚麼第一題會被打錯嗎?
我的寫法:
str_smallClosest<-function(chrNumber,criticalNumber){
  as.numeric(chrNumber)->numNumber
  logiTrue<- chrNumber <=criticalNumber
  max(numNumber[logiTrue])->MaxNum
  return(as.character(MaxNum))
}
str_smallClosest
參考答案:
str_smallClosest <- function(chrNumber,criticalNumber){
  as.numeric(chrNumber) -> numNumber
  logiTrue <- numNumber <= criticalNumber
  max(numNumber[(numNumber <= criticalNumber)]) -> maxNum
  return(as.character(maxNum))
}

str_smallClosest
謝謝老師

**Comment by tpemartin** [comment]
```
logiTrue<- chrNumber <=criticalNumber # 錯誤
logiTrue<- numNumber <=criticalNumber # 正確
```
因為犯了字串比數字的觀念錯誤，所以無法部份給分，但很高興你有問——相信以後不會再有同樣錯誤。👍🏽
